### PR TITLE
Add PS2000a AWG software trigger and API function

### PR DESCRIPTION
**Pull request by richardbarlow**

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Looks good! thanks.

We really should get a changelog going.

**Comment by hmaarrfk** [comment]
You should be able to depend on 0.7.4 for your projects.

**Comment by richardbarlow** [comment]
Fantastic! Thank you for the amazingly quick response!

**Comment by hmaarrfk** [comment]
You'll probably just find it easier to stay on the git clone, because you will add other things. Always glad to help other researchers !

**Pull request merged**
