### PR TITLE
implement bandwidthlimit for 5000-series

### PR DESCRIPTION
**Pull request by arunpersaud**
Actually set the bandwidthlimit for the 5000-series. The function already had the bwlimit argument, but it doesn't seem to be used.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Thanks for the patch, is it possible to remove the logic in the lowlevel function.
from
if...
else
m = self.lib.ps5000aSetBandwidthFilter(c_int16(self.handle), c_enum(chNum), c_enum(0))

to simply 
m = self.lib.ps5000aSetBandwidthFilter(c_int16(self.handle), c_enum(chNum), c_enum(BWLimited))

**Comment by hmaarrfk** [comment]
Can you also add logic in the picobase module to deal with the input of strings "BW_FULL" and "BW_20MHZ" as well as 0 and 1. There are examples of how we did this in the setChannel function itself.

While you are doing this, please change the default value of BWLimited from false to 0. Some scopes actually have 3 different options.... (will explain in the next post).

**Comment by hmaarrfk** [comment]
I forget the specifics of why it wasn't implemented in the ps5000 series, but I have a small issue:

BW Limitting is actually a separate API call to to the USB device. This means that in the case that the second API call fails, we should think of how to deal with the error. 
a) Do we rollback the previous call? Might be complicated and unecessary. Also API calls are slow, we want to avoid them.
Do you change the order of how you call things to make it easier to rollback the bandwidth of the channel as opposed to the 10 other settings set by the "setChannel" command?

b) We have avoided doing many of the "sanity checks" because the API does a good job at it. It feels redundant (and unmanageable) to do all the sanity checking ourselves. In the case of the PS5000, this seems like the options for the BW limiter are less complicated than the PS6000. It might be a good idea to do a quick check before any of the API is invoked and throw your own error before proceeding.

**Comment by arunpersaud** [comment]
thanks for the comments. I'll be on travel for a month, will look at this once I'm back.

**Comment by hmaarrfk** [comment]
See Issue #54

**Pull request closed without merging**
