### PR TITLE
Fix loading of DLLs on windows by adding a call to find_library()

### PR DESCRIPTION
**Pull request by Cyclical-**
This change fixes the inability of windll.LoadLibrary() to locate the PicoSDK dlls by adding a call to ctypes.util.find_library(). For this to work either the installed PicoSDK bitness must be the same as the python bitness, or if both SDK versions are installed the equal bitness version must be first in the system PATH.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Thanks for the contribution.


I'm sorry to ask, but could you undo much of the formatting changes you made? I feel like you had your editor on auto format

**Comment by Cyclical-** [comment]
Oops, my bad. Must have happened when I ran ```black``` to format for PEP8.

**Comment by Cyclical-** [comment]
By the way, this should likely close issue #155

**Comment by hmaarrfk** [comment]
Closes #155

**Comment by hmaarrfk** [comment]
Thanks for going through all of them.

**Comment by hmaarrfk** [comment]
Version 0.7.12 should have what you need (though I might release 0.7.13 soon)

**Pull request merged**
