### PR TITLE
Fix to issue #169

### PR DESCRIPTION
**Pull request by elechapt**
This code fix the issue #169. Tested and functional with linux x64 and picoscope PS5000a

### CODE REVIEW

**Comment by hmaarrfk** [comment]
is this a problem for all devices? is there a way for us to do this for all of them in 1 line of code like you did just now?

**Comment by elechapt** [comment]
By other device, do you mean the PS*000a ?
I don't know, but it should be a problem for all serial number initialized devices (seems that the PS*000 are not concerned, just the -a serie) since the problem comes from (afaik) the fact that `create_string_buffer` in python 3.x must take strings as byte object, and all the PS*000a does initialize `serialNullTermStr` with that line. Even if in some cases it is wrapped in `byref` function.

As I do not have others picoscope, I can't test it, but wrapping `sn` with the `bytes` function should solve this problem (if existing) for all devices.

**Comment by bmoneke** [comment]
> is this a problem for all devices? is there a way for us to do this for all of them in 1 line of code like you did just now?

I tested the ps4824 (with ps4000a.py): right now the code uses ``create_string_buffer(str(sn))``, which does not work raising a TypeError. Once I changed the corresponding line (line 146) to ``serialNullTermStr = create_string_buffer(bytes(sn, encoding='utf-8'))``, it works.

The other open method (openAsync) is affected as well.

Unfortunately I don't know, how to include this change without creating another pull request.

**Comment by hmaarrfk** [comment]
Out of curiosity, what version of python are you all using? I swear i used to use python 3 and this wasn't an issue. Maybe I just never used serial numbers.

**Comment by hmaarrfk** [comment]
@elechapt  @bmoneke sorry i let this one drop.

I think this is ready for merging, but our CIs are down https://github.com/colinoflynn/pico-python/issues/172


And i don't want to merge without them up (i can't create a release without them).

**Comment by bmoneke** [comment]
Shall I make a separate pull request for the 4000a?

I have another fix in the pipeline, where I could include it as well.

> Out of curiosity, what version of python are you all using? I swear i used to use python 3 and this wasn't an issue. Maybe I just never used serial numbers.

I tested it on python 3.9.

**Comment by elechapt** [comment]
I tried on python3.7, 3.8, 3.9. That's rignt, only happens when you specify a serial number.

**Comment by hmaarrfk** [comment]
let's pray this doesn't break 2.7 if anybody is still using it.

**Comment by hmaarrfk** [comment]
look out of for 0.7.16

**Comment by elechapt** [comment]
Ah, about breaking python 2.x, it does, because of the way that bug occurs, as I explained above. 
2.x makes an assomption that 3.x does not, that's why bug, that's why break. But hopefully, no one uses 2.x.

**Comment by hmaarrfk** [comment]
I think @colinoflynn does use 2.x but alas, he can pin to an old version :D. He indicated that this was OK in a previous comment.

**Comment by elechapt** [comment]
Yeah, that's why I was in the branch python_37.

**Comment by hmaarrfk** [comment]
oh.... i didn't even know that existed.

Do you want to make the PR to the main branch. I don't think the python_37 branch is active.

Lets just break python 2.7 support.

**Comment by colinoflynn** [comment]
Yeah I've given up on 2.7 with everything else I do now ;-) So I'd say break the main one, no need to keep 2.7!

**Comment by colinoflynn** [comment]
...and if I ever need some 2.7 it's for recreating old results, so I'll need to use old versions of the library anyway

**Pull request merged**
