### PR TITLE
Fix: timebase ps4000a

### PR DESCRIPTION
**Pull request by NINI1988**
The timebase calculation for ps4000a devices was wrong:
See 3.7 Timebases from https://www.picotech.com/download/manuals/picoscope-4000-series-a-api-programmers-guide.pdf.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
you believe that the 4824 and the 4000a are the same. is that correct?

**Comment by NINI1988** [comment]
In the documentation `PicoScope 4824 and 4000A Series` are in the same Timebase calculation table. Only the `PicoScope 4444` is different. 
Also the calculation of the existing `4824` code matches my calculation and the datasheet, so I have combined them.
I have removed the `4828` because I can't find it on google and does not exists in the programmers api guide.

So yes I believe they are the same for the timebase calculation

**Comment by NINI1988** [comment]
Could you please release a new version, so the 4000 series can be used easily. Thank you.

**Comment by hmaarrfk** [comment]
Sorry for the delay: https://github.com/colinoflynn/pico-python/releases/tag/0.7.28

**Comment by BenediktBurger** [comment]
Thanks for cleaning up the code.

**Pull request merged**
