### PR TITLE
Adding PS2000A and PS3000 series

### PR DESCRIPTION
**Pull request by amccaugh**
It turns out the PS2000A is nearly identical to the PS3000A code, and the PS3000 code is nearly identical to the PS3000A code.  This code works well enough to operate the ps2000_demo.py with the ps2000a and I've fixed a few bugs that I ran across along the way.

### CODE REVIEW

**Comment by colinoflynn** [comment]
Looks reasonable to me thanks! I'll check if @hmaarrfk sees any issues and if I don't hear anything merge it in.

**Comment by hmaarrfk** [comment]
Looks good. I wonder if there is a way to call things using strings. With string concatenation we can probably get rid of many copies of the same code.

**Comment by hmaarrfk** [comment]
I imagine there would be many edge cases that arrise when functions change naming conventions or constants change between models of the picoscope. I almost prefer it this way because we are forced to go through the programming manual line by line almost.

**Comment by colinoflynn** [comment]
Yeah - I had the exact same thought as you ;-) At first "we can make a more general call structure with lists of functions" or something, but then realized there ARE little changes between variants even in expected data format.

The "low-level" files are a little large, but at least it helps guarantee we have a constant match between the actual DLL api functions. There's probably something smart we could do with a base classes, but I do agree with you that the pain caused by our current method might be a good thing sometimes...

**Comment by amccaugh** [comment]
Yup I think it's just a matter of choosing whether it's more convenient to change a couple files at a time with the same code, or to write some clever variant-reproducing code and make sure it doesn't break.  I think the former is probably better in this case

**Pull request merged**
