### PR TITLE
Work around SIP on macOS

### PR DESCRIPTION
**Pull request by aarmea-butterfly**
This change fixes library loading problems that occur on macOS with SIP
enabled by temporarily patching Pico's libraries to use absolute paths.
This is an automated implementation of the workaround described at
<http://ulthiel.com/vk2utl/picoscope-python-interface-under-mac-os-x/>
improved to not break PicoScope6.app itself.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
awesome work! can you potentially move it out of picobase? maybe create a new file called `util.py` or `darwin_utils.py`.

I don't think you are using the self keyword anyway, seems like it could be a simple function.

my goal is to have people not think at all about `ctypes` in `picobase` as that is really an implementation detail.

**Comment by hmaarrfk** [comment]
Fine, good enough. It is at the bottom of the file so I dont care too much.

want to add 

```
try:
    FileNotFoundError
except NameError:
    FileNotFoundError = IOError
```

somewhere in the function to make sure it works with 2.7. This is almost enough for me to want to drop 2.7, but that is a decision for a later day.

**Comment by aarmea-butterfly** [comment]
I don't have too much more time to look at this today, but my thoughts on Python 2.7 are that it's a little more pesky than just `FileNotFoundError` -- there's also `tempfile.TemporaryDirectory` which provides a temporary directory that's deleted once it falls out of scope, and `subprocess.run` which isn't too different from `subprocess.check_call`.

**Comment by aarmea-butterfly** [comment]
I only tested this on my macOS 10.13.4 machine with Python 3.6.3. That said, my new 2.7-incompatible code is only ever imported on macOS, so it shouldn't impact 2.7 compatibility on any other OS. In addition, it only tries to use the incompatible features if SIP is enabled.

**Comment by hmaarrfk** [comment]
Right, so I'm inclined to pull this in even if it "doesn't fully work with 2.7".

When picotech will fix their issue, then we can more or less jsut delete the `utils_darwin.py` you added.

**Comment by hmaarrfk** [comment]
Thanks, this should now be enabled in `0.7.3` when it gets uploaded on PyPi. I fixed 2 things to get flake8 to pass. I hope that didn't break things

**Comment by aarmea-butterfly** [comment]
Thanks! I just tested it with the published version and it still works fine.

**Pull request merged**
